import type { Locale } from '$lib/playback/engine';

const en = {
  title: 'Qwen Inference Atlas',
  subtitle: 'One real Ascend NPU trace, explained step by step',
  real: 'Captured', derived: 'Derived', captured: 'Captured', summary: 'Summary', structural: 'Structural', schematic: 'Schematic',
  overview: 'Overview', init: 'Initialize', tokens: 'Tokenize', prefill: 'Prefill', attention: 'Attention', moe: 'MoE + W8A8', tp: 'Tensor Parallel', decode: 'Decode',
  play: 'Play inference', pause: 'Pause inference', runOneStep: 'Run one step', previous: 'Previous chapter', next: 'Next chapter', evidence: 'Evidence', language: '中文', close: 'Close',
  startTrace: 'Play inference', playbackSpeed: 'Playback speed', recordedPrompt: 'Recorded prompt', currentScene: 'Current scene', viewing: 'Viewing', inferenceCursor: 'Cursor', playbackControls: 'Trace playback controls', traceChapters: 'Trace chapters',
  playbackOptions: 'Playback options', startPosition: 'Start position', fromBeginning: 'From beginning', fromCurrentPage: 'From current page', fromCurrentStep: 'From current step', runMode: 'Run mode', continuous: 'Continuous', singleStep: 'Single step',
  fromBeginningHint: 'Reset and start at model initialization.', fromCurrentPageHint: 'Start this visible chapter at 0%.', fromCurrentStepHint: 'Resume the independent inference cursor.',
  heroKicker: 'RECORDED TRACE · QWEN3.5 · ASCEND NPU', heroTitle: 'Watch one real inference unfold', heroBody: 'Follow weights into NPU memory, turn five tokens into matrices, and trace the two-rank path to the next five tokens.',
  globalFlowTitle: 'The whole inference, at a glance', globalFlowBody: 'Play the trace for a guided tour, scroll at your own pace, or click a stage to move directly into its evidence.',
  prompt: 'Prompt', output: 'Generated output', model: 'Model', execution: 'Execution',
  loadWeights: 'Load weights', checkpointShards: 'checkpoint shards', promptTokens: 'prompt tokens', capturedTensor: 'Captured embedding tensor', transformerLayers: 'Transformer stack', layers: 'layers', linearShort: 'linear', fullShort: 'full', logits: 'Logits', greedySelection: 'Greedy top-1 selection', completion: 'Completion', generatedTokens: 'generated tokens', exactOutput: 'Exact output', embedding: 'Embedding',
  initKicker: '01 · INITIALIZATION', initTitle: 'Before the first token, the model becomes runnable', initBody: 'Configuration creates the 40-layer skeleton. Ten W8A8 checkpoint shards are mapped across two ranks, KV cache is prepared, and the runtime reaches READY.',
  initializationSequence: 'Initialization sequence', config: 'Config', layerSkeleton: '40-layer skeleton', quantization: 'Quantization', parameterMapping: 'Parameter mapping', kvCache: 'KV cache', runtimeProbe: 'Runtime probe', readyState: 'READY',
  hiddenSize: 'Hidden size', vocabulary: 'Vocabulary', attentionHeads: 'Attention heads', experts: 'experts', layersOverview: '40-layer architecture', linearAttention: 'Linear attention', fullAttention: 'Full attention', quantizedLeaves: 'W8A8 leaves', floatLeaves: 'floating leaves', notAllInt8: 'W8A8 is selective: floating-point modules remain.', localShard: 'local parameter shard', runtimeState: 'NPU runtime state', graphBaselineNote: 'Graph capture belongs to the optimized baseline; this p4r4 deep trace uses eager observability.', readyForPrompt: 'Two ranks are ready for the recorded prompt.',
  tokenKicker: '02 · TOKENIZATION', tokenTitle: 'Five text pieces become a [5, 2048] matrix', tokenBody: 'The tokenizer emits exact integer IDs. Embedding lookup expands each ID into one 2,048-dimensional row.', tokenIds: 'Token IDs', embeddingMatrix: 'Embedding matrix', shape: 'Shape', scheduler: '1 request · 5 prompt tokens · execution padded to 8',
  prefillKicker: '03 · PREFILL', prefillTitle: 'Five positions travel through all 40 layers', prefillBody: 'Thirty layers use linear attention and ten use full attention. Layer 3 exposes the captured Q/K/V path used by the detailed scenes below.', hidden: 'Hidden states', norm: 'RMSNorm', qkv: 'Fused QKV projection', fivePositions: '5 positions', layerStack: '40-layer path',
  linearLayerTitle: 'Layer 0 · Gated DeltaNet', expandLinearAttention: 'Explore linear attention', openFullAttention: 'Open the full-attention microscope', linearAttentionEntryHint: 'Open captured boundary summaries and the source-level recurrent path', linearAttentionInternals: 'Linear attention internals', linearAttentionFocusHint: 'Captured tensor summaries bracket the source-derived Gated DeltaNet path.', linearAttentionSequence: 'Linear-attention sequence', capturedInput: 'Captured layer input', qkvzbaProjection: 'QKV + Z + β + α projection', causalConv1d: 'Causal Conv1D', gatedDeltaRule: 'Gated delta recurrence', gatedNormProjection: 'Gated norm + output projection', capturedOutput: 'Captured layer output', recurrentState: 'Recurrent SSM state', sourceLevelPath: 'Source-level operator path', boundaryOnly: 'Only bounded samples and statistics were retained for the captured layer boundaries; internal operator motion is schematic.', rankBoundaryCapture: 'Rank 0 boundary summary', tensorStatistics: 'Tensor statistics', minimum: 'Minimum', maximum: 'Maximum', mean: 'Mean', standardDeviation: 'Std. deviation',
  attentionKicker: '04 · ATTENTION', attentionTitle: 'Attention under the microscope', attentionBody: 'Captured Q/K/V drive a causal attention reconstruction. Scores, mask, softmax and weighted output are derived offline, then verified against the fused kernel output.',
  expandAttention: 'Explore attention internals', inputTokens: 'Input tokens', meanAttention: 'Mean of 16 heads', attentionEntryHint: 'Open the complete Q → scores → mask → softmax → output path', attentionInternals: 'Attention internals', headSelectorHint: 'Choose any real head, then play or select a stage.', previousHead: 'Previous attention head', nextHead: 'Next attention head', head: 'Head', attentionSequence: 'Attention sequence', capturedQkv: 'Captured Q / K / V', attentionScores: 'Attention scores', scaleAndMask: 'Scale + causal mask', softmax: 'Softmax probabilities', weightedOutput: 'Weighted sum + output', playSequence: 'Play sequence', futureBlocked: 'Future positions are blocked before softmax.', rowsSumOne: 'Each visible row sums to 1.', derivedOutput: 'Derived softmax × V', fusedOutput: 'Captured fused output', cosineSimilarity: 'cosine similarity', verifiedAgainstFused: 'verified against fused output', causalMask: 'Causal mask',
  moeKicker: '05 · MIXTURE OF EXPERTS', moeTitle: 'A sparse route through 256 experts', moeBody: 'Every prompt token receives 256 router scores. The real top-8 route expands to 40 token-expert rows, is dynamically quantized, processed by two grouped matmuls, and combined.',
  router: 'Router scores', topEight: 'Top-8 experts', dispatch: 'Dispatch 5 × 8 rows', dynamicScale: 'Per-token dynamic scale', gmm1Swiglu: 'GMM1 + SwiGLU', gmm2Combine: 'GMM2 + combine', expandMoe: 'Explore MoE + W8A8', onlyEightActive: 'Only the selected path is emphasized', moeEntryHint: 'Open routing weights, quantization scales and grouped matmuls', moeInternals: 'MoE + W8A8 internals', moeFocusHint: 'Switch token and rank without leaving the trace.', selectToken: 'Select prompt token', selectRank: 'Select tensor-parallel rank', moeSequence: 'MoE sequence', routerScoresAllExperts: 'One [5, 256] router tensor scores every expert.', combine: 'Weighted combine', weightedExpertsReturn: 'Forty expert rows return to five hidden-state rows.', moeCapturedBoundary: 'Captured Python-visible fusion boundaries.', kernelInteriorNotDumped: 'Kernel workspaces are not presented as captured data.',
  tpKicker: '06 · TENSOR PARALLELISM', tpTitle: 'Parallel work, one logical result', tpBody: 'TP=2 splits projection weights across two Ascend workers. Both lanes advance together, synchronize at collective boundaries, and expose identical logical logits.',
  weightShard: 'Weight shard', localQkv: 'Local QKV', localAttention: 'Local attention', localMoe: 'Local MoE', collective: 'Collective', localLogits: 'Local logits', mergedResult: 'Merged result', localOutput: 'Local output', expandTp: 'Explore tensor parallelism', tpEntryHint: 'Open the two synchronized rank lanes', tpInternals: 'Tensor parallel internals', tpFocusHint: 'Real rank spans are shown in parallel; collective motion is explanatory.', tpSequence: 'Tensor-parallel sequence', syncRanks: 'synchronize ranks', capturedRankOutput: 'captured on this rank', merge: 'Merge', tpCapturedSpans: 'Captured rank-local tensors and spans.', collectiveTeachingMotion: 'Collective packet motion is schematic.',
  decodeKicker: '07 · DECODE', decodeTitle: 'Five exact next-token decisions', decodeBody: 'Each decode step produces [1, 248320] logits, selects the captured top-1 token, reuses KV cache, and advances the output by one token.', selectedToken: 'Selected token', reuseState: 'reused state grows each step', generatedText: 'Generated text', schematicReveal: 'Schematic reveal', finalStringCaptured: 'The complete string is shown only after all five captured token IDs complete.', textRevealNote: 'Character reveal is explanatory; token IDs and the final string are exact.', decodeSteps: 'Five decode steps', step: 'Step',
  traceEvidence: 'Trace evidence', provenance: 'Provenance', runId: 'Run ID', eventCount: 'Structured events', sourceFiles: 'Source artifacts', tensorInspector: 'Tensor inspector', glossary: 'Glossary', dtype: 'Data type', device: 'Device', semantics: 'Meaning', loading: 'Loading real trace…', error: 'Trace unavailable', retry: 'Retry', methodNote: 'This is a static player for a recorded trace. No model runs in the browser.',
  evidenceExecutionValue: 'vLLM Ascend · 2 NPU ranks · eager observability', evidenceProvenance: 'Exact values, captured tensor summaries, verified derived attention, structural config and explicitly schematic teaching motion.', capturedDefinition: 'Complete directly captured values from p4r4.', summaryDefinition: 'Statistics and bounded samples of a directly captured tensor.', derivedDefinition: 'Deterministic computation from real inputs, verified against captured output.', structuralDefinition: 'Model configuration and source-level structure.', schematicDefinition: 'Teaching motion without a claim of captured intermediate values.'
} as const;

export type MessageKey = keyof typeof en;

const zhCN: Record<MessageKey, string> = {
  title: 'Qwen 推理图谱',
  subtitle: '逐步拆解一次真实的昇腾 NPU 推理轨迹',
  real: '真实采集', derived: '离线推导', captured: '真实采集', summary: '真实摘要', structural: '确定结构', schematic: '教学示意',
  overview: '总览', init: '初始化', tokens: '分词', prefill: '预填充', attention: '注意力', moe: 'MoE + W8A8', tp: '张量并行', decode: '逐词生成',
  play: '播放推理', pause: '暂停推理', runOneStep: '执行单步', previous: '上一章节', next: '下一章节', evidence: '数据证据', language: 'EN', close: '关闭',
  startTrace: '播放推理', playbackSpeed: '播放速度', recordedPrompt: '录制输入', currentScene: '当前场景', viewing: '当前页面', inferenceCursor: '推理游标', playbackControls: '轨迹播放控制', traceChapters: '轨迹章节',
  playbackOptions: '播放选项', startPosition: '开始位置', fromBeginning: '从头开始', fromCurrentPage: '从当前页面开始', fromCurrentStep: '从当前步骤继续', runMode: '执行模式', continuous: '连续播放', singleStep: '单步执行',
  fromBeginningHint: '重置并从模型初始化开始。', fromCurrentPageHint: '从当前可见章节的 0% 开始。', fromCurrentStepHint: '继续独立的推理步骤游标。',
  heroKicker: '真实轨迹 · QWEN3.5 · 昇腾 NPU', heroTitle: '观看一次真实推理完整展开', heroBody: '跟随权重进入 NPU 内存，把五个 Token 变成矩阵，再沿双 Rank 路径得到后续五个 Token。',
  globalFlowTitle: '先看完整推理全貌', globalFlowBody: '播放轨迹可跟随引导，也可以自行滚动，或点击任一阶段直接进入其真实证据。',
  prompt: '输入文本', output: '生成结果', model: '模型', execution: '执行环境',
  loadWeights: '加载权重', checkpointShards: '个权重分片', promptTokens: '个输入 Token', capturedTensor: '真实采集的 Embedding', transformerLayers: 'Transformer 层栈', layers: '层', linearShort: '线性注意力', fullShort: '全注意力', logits: 'Logits', greedySelection: '贪心 Top-1 选择', completion: '生成文本', generatedTokens: '个生成 Token', exactOutput: '精确输出', embedding: 'Embedding',
  initKicker: '01 · 初始化', initTitle: '第一个 Token 进入前，模型先变成可运行状态', initBody: '配置建立 40 层骨架，10 个 W8A8 权重分片映射到两个 Rank，随后准备 KV Cache 和运行时，最终到达 READY。',
  initializationSequence: '初始化顺序', config: '配置', layerSkeleton: '40 层骨架', quantization: '量化描述', parameterMapping: '参数映射', kvCache: 'KV Cache', runtimeProbe: '运行时探针', readyState: '就绪',
  hiddenSize: '隐藏维度', vocabulary: '词表大小', attentionHeads: '注意力头', experts: '个专家', layersOverview: '40 层结构', linearAttention: '线性注意力', fullAttention: '全注意力', quantizedLeaves: 'W8A8 叶模块', floatLeaves: '浮点叶模块', notAllInt8: 'W8A8 是选择性路径，部分模块仍保持浮点。', localShard: '本地参数分片', runtimeState: 'NPU 运行时状态', graphBaselineNote: 'Graph Capture 属于优化 baseline；本次 p4r4 深层轨迹采用 eager 可观察模式。', readyForPrompt: '两个 Rank 已准备好处理录制输入。',
  tokenKicker: '02 · 分词', tokenTitle: '五段文本变成 [5, 2048] 矩阵', tokenBody: 'Tokenizer 产生精确整数 ID，Embedding 查表再把每个 ID 扩展为一行 2,048 维向量。', tokenIds: 'Token ID', embeddingMatrix: 'Embedding 矩阵', shape: '形状', scheduler: '1 个请求 · 5 个输入 Token · 执行补齐到 8',
  prefillKicker: '03 · 预填充', prefillTitle: '五个位置穿过全部 40 层', prefillBody: '其中 30 层使用线性注意力，10 层使用全注意力。第 3 层暴露了下方详情所使用的真实 Q/K/V 路径。', hidden: '隐藏状态', norm: 'RMSNorm', qkv: '融合 QKV 投影', fivePositions: '5 个位置', layerStack: '40 层路径',
  linearLayerTitle: '第 0 层 · Gated DeltaNet', expandLinearAttention: '展开线性注意力', openFullAttention: '打开全注意力显微视图', linearAttentionEntryHint: '打开真实边界摘要与源码级循环路径', linearAttentionInternals: '线性注意力内部过程', linearAttentionFocusHint: '真实 Tensor 摘要包围源码推导的 Gated DeltaNet 路径。', linearAttentionSequence: '线性注意力计算顺序', capturedInput: '真实层输入', qkvzbaProjection: 'QKV + Z + β + α 投影', causalConv1d: '因果 Conv1D', gatedDeltaRule: '门控 Delta 循环', gatedNormProjection: '门控归一化 + 输出投影', capturedOutput: '真实层输出', recurrentState: '循环 SSM 状态', sourceLevelPath: '源码级算子路径', boundaryOnly: '层输入/输出仅保留受控长度样本与统计；内部算子运动为教学示意。', rankBoundaryCapture: 'Rank 0 边界摘要', tensorStatistics: 'Tensor 统计', minimum: '最小值', maximum: '最大值', mean: '均值', standardDeviation: '标准差',
  attentionKicker: '04 · 注意力', attentionTitle: '在显微镜下观察 Attention', attentionBody: '真实 Q/K/V 驱动因果注意力重建。Scores、Mask、Softmax 和加权输出在离线确定性计算后，与融合内核输出进行验证。',
  expandAttention: '展开 Attention 内部', inputTokens: '输入 Token', meanAttention: '16 个 Head 平均值', attentionEntryHint: '打开完整的 Q → Scores → Mask → Softmax → Output 路径', attentionInternals: 'Attention 内部过程', headSelectorHint: '选择任一真实 Head，然后播放或直接选择步骤。', previousHead: '上一个 Attention Head', nextHead: '下一个 Attention Head', head: 'Head', attentionSequence: 'Attention 计算顺序', capturedQkv: '真实 Q / K / V', attentionScores: '注意力分数', scaleAndMask: '缩放 + 因果遮罩', softmax: 'Softmax 概率', weightedOutput: '加权求和 + 输出', playSequence: '播放过程', futureBlocked: '未来位置在 Softmax 前被屏蔽。', rowsSumOne: '每个可见行的概率和为 1。', derivedOutput: '推导的 Softmax × V', fusedOutput: '真实融合输出', cosineSimilarity: '余弦相似度', verifiedAgainstFused: '已与融合输出验证', causalMask: '因果遮罩',
  moeKicker: '05 · 混合专家', moeTitle: '穿过 256 个专家中的一条稀疏路径', moeBody: '每个输入 Token 都会获得 256 个路由分数，真实 Top-8 展开为 40 行 Token-Expert 数据，经动态量化和两次分组矩阵乘后再合并。',
  router: '路由分数', topEight: 'Top-8 专家', dispatch: '分发 5 × 8 行', dynamicScale: '逐 Token 动态 Scale', gmm1Swiglu: 'GMM1 + SwiGLU', gmm2Combine: 'GMM2 + 合并', expandMoe: '展开 MoE + W8A8', onlyEightActive: '只强调当前选中的计算路径', moeEntryHint: '打开路由权重、量化 Scale 和分组矩阵乘', moeInternals: 'MoE + W8A8 内部过程', moeFocusHint: '无需离开轨迹即可切换 Token 和 Rank。', selectToken: '选择输入 Token', selectRank: '选择张量并行 Rank', moeSequence: 'MoE 计算顺序', routerScoresAllExperts: '一个 [5, 256] 路由 Tensor 为全部专家评分。', combine: '加权合并', weightedExpertsReturn: '40 行专家结果重新合并为 5 行隐藏状态。', moeCapturedBoundary: '真实采集 Python 可见的融合边界。', kernelInteriorNotDumped: '未把内核 Workspace 冒充成真实采集数据。',
  tpKicker: '06 · 张量并行', tpTitle: '两路并行工作，得到一个逻辑结果', tpBody: 'TP=2 把投影权重分给两个昇腾 Worker。两条轨道同时推进，在集合通信边界同步，并产生一致的逻辑 Logits。',
  weightShard: '权重分片', localQkv: '本地 QKV', localAttention: '本地 Attention', localMoe: '本地 MoE', collective: '集合通信', localLogits: '本地 Logits', mergedResult: '合并结果', localOutput: '本地输出', expandTp: '展开张量并行', tpEntryHint: '打开两条同步的 Rank 轨道', tpInternals: '张量并行内部过程', tpFocusHint: '并排展示真实 Rank Span；集合通信动画用于教学解释。', tpSequence: '张量并行顺序', syncRanks: '同步两个 Rank', capturedRankOutput: '该 Rank 真实采集', merge: '合并', tpCapturedSpans: '真实采集 Rank 本地 Tensor 和 Span。', collectiveTeachingMotion: '集合通信数据包运动为教学示意。',
  decodeKicker: '07 · 逐词生成', decodeTitle: '五次精确的下一 Token 决策', decodeBody: '每个 Decode 步骤产生 [1, 248320] Logits，选择真实 Top-1 Token，复用 KV Cache，并让输出前进一个 Token。', selectedToken: '选中 Token', reuseState: '每一步继续复用并增长', generatedText: '生成文本', schematicReveal: '字符展开示意', finalStringCaptured: '只有五个真实 Token ID 全部完成后才显示完整精确字符串。', textRevealNote: '中间字符展开用于解释；Token ID 和最终字符串为精确数据。', decodeSteps: '五个 Decode 步骤', step: '步骤',
  traceEvidence: '轨迹证据', provenance: '数据来源', runId: '运行 ID', eventCount: '结构化事件', sourceFiles: '数据文件', tensorInspector: '张量检查器', glossary: '术语表', dtype: '数据类型', device: '设备', semantics: '含义', loading: '正在加载真实轨迹…', error: '轨迹加载失败', retry: '重试', methodNote: '这是录制轨迹的静态播放器，浏览器内不会运行模型。',
  evidenceExecutionValue: 'vLLM Ascend · 2 个 NPU Rank · eager 可观察模式', evidenceProvenance: '精确值、真实 Tensor 摘要、经验证的离线 Attention、确定配置结构，以及明确标记的教学示意运动。', capturedDefinition: '来自 p4r4 的完整直接采集值。', summaryDefinition: '直接采集 Tensor 的统计与受控长度样本。', derivedDefinition: '由真实输入确定性计算，并与采集输出完成验证。', structuralDefinition: '来自模型配置与源码层面的确定结构。', schematicDefinition: '用于教学的运动，不声称是采集到的中间值。'
};

export const messages: Record<Locale, Record<MessageKey, string>> = { en, 'zh-CN': zhCN };
export const createCatalog = (locale: Locale) => (key: MessageKey) => messages[locale][key];
